// Generated by uniffi-bindgen-react-native
#include "veloqrs.h"
#include "generated/veloqrs.hpp"

namespace veloqrs {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeVeloqrs::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}