// Generated by scripts/generate-trend-table.ts. Do not edit.
// Source: modules/veloqrs/rust/veloqrs/src/trend_table.rs, `TREND_METRICS`.
// Regenerate with `npm run config:trend`.

/**
 * How much each metric has to move before it reads as a move at all.
 *
 * The units are the metric's own: points of CTL, hours, whole activities,
 * watts, minutes of pace (per kilometre, or per 100 m for CSS), beats,
 * kilograms. Pace is pace, not the critical speed it comes from.
 */
export const TREND_DEADBAND = {
  /** CTL and ATL are integers, so under a point is not a move. */
  fitness: 1,
  fatigue: 1,
  /** Form is a difference of two, so it carries twice the noise. */
  form: 2,
  weekHours: 0.5,
  weekCount: 1,
  /** Kilometres, and load in the server's own points. */
  weekDistance: 1,
  /** Load is fatigue's number, so it moves with no judgement, as fatigue does. */
  weekTss: 5,
  /** change of its two-week averages, and read only the polarity from here. */
  weekSets: 1,
  ftp: 2,
  /** Three seconds a kilometre, and three seconds a hundred metres for CSS. */
  thresholdPace: 0.05,
  css: 0.05,
  hrv: 2,
  rhr: 1,
  weight: 0.3,
} as const;

/** A metric with a threshold of its own. */
export type TrendMetric = keyof typeof TREND_DEADBAND;

/**
 * Which way is better, one entry per metric with a deadband, so a surface
 * never judges a number locally. A pace is minutes per unit distance, so it
 * falls to improve. `none` is a metric with a direction and no judgement: weight,
 * fatigue and form are drawn the way intervals.icu draws them, as a bare arrow
 * on the neutral rung, and form's colour is its zone rather than its move.
 */
export const TREND_POLARITY: Record<TrendMetric, 'higher' | 'lower' | 'none'> = {
  fitness: 'higher',
  fatigue: 'none',
  form: 'none',
  weekHours: 'higher',
  weekCount: 'higher',
  weekDistance: 'higher',
  weekTss: 'none',
  weekSets: 'none',
  ftp: 'higher',
  thresholdPace: 'lower',
  css: 'lower',
  hrv: 'higher',
  rhr: 'lower',
  weight: 'none',
};
