// Generated by uniffi-bindgen-react-native
// Patched for React Native 0.81+ compatibility (CallInvokerHolder changes)
#include <jni.h>
#include <jsi/jsi.h>
#include <fbjni/fbjni.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "veloqrs.hpp"

namespace jsi = facebook::jsi;
namespace react = facebook::react;
namespace jni = facebook::jni;

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_veloq_VeloqrsModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    auto callInvokerHolder = jni::static_ref_cast<react::CallInvokerHolder::javaobject>(
        jni::make_local(callInvokerHolderJavaObj)
    );
    auto jsCallInvoker = callInvokerHolder->cthis()->getCallInvoker();

    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    NativeVeloqrs::registerModule(*runtime, jsCallInvoker);
    return true;
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_veloq_VeloqrsModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    NativeVeloqrs::unregisterModule(*runtime);
    return true;
}
