// Generated by uniffi-bindgen-react-native
package com.veloq

import com.facebook.react.TurboReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.model.ReactModuleInfo
import com.facebook.react.module.model.ReactModuleInfoProvider
import com.facebook.react.uimanager.ViewManager
import java.util.HashMap

class VeloqrsPackage : TurboReactPackage() {
  override fun getModule(name: String, reactContext: ReactApplicationContext): NativeModule? {
    return if (name == VeloqrsModule.NAME) {
      VeloqrsModule(reactContext)
    } else {
      null
    }
  }

  // Not generated. The map's tile interceptor is a WebViewClient, and only a
  // view manager of ours can attach it, so it is registered beside TileBridge
  // rather than in a module of its own.
  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
    return listOf(VeloqWebViewManager())
  }

  override fun getReactModuleInfoProvider(): ReactModuleInfoProvider {
    return ReactModuleInfoProvider {
      val moduleInfos: MutableMap<String, ReactModuleInfo> = HashMap()
      moduleInfos[VeloqrsModule.NAME] = ReactModuleInfo(
        VeloqrsModule.NAME,
        VeloqrsModule.NAME,
        false,  // canOverrideExistingModule
        false,  // needsEagerInit
        false,  // isCxxModule
        true // isTurboModule
      )
      moduleInfos
    }
  }
}