// Dark Matter style adapted for OpenFreeMap tiles
// Original style: https://github.com/openmaptiles/dark-matter-gl-style (BSD license)
// Tiles: OpenFreeMap (MIT license)
// Cartography: Based on CartoDB Dark Matter by Stamen Design (CC0)

export const DARK_MATTER_STYLE = {
  version: 8 as const,
  name: 'Dark Matter',
  sources: {
    openmaptiles: {
      type: 'vector' as const,
      url: 'https://tiles.openfreemap.org/planet',
    },
  },
  sprite: 'https://openmaptiles.github.io/dark-matter-gl-style/sprite',
  glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
  layers: [
    {
      id: 'background',
      type: 'background' as const,
      paint: { 'background-color': 'rgb(12,12,12)' },
    },
    {
      id: 'water',
      type: 'fill' as const,
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: ['all', ['==', '$type', 'Polygon'], ['!=', 'brunnel', 'tunnel']],
      paint: { 'fill-antialias': false, 'fill-color': 'rgb(27,27,29)' },
    },
    {
      id: 'landcover_ice_shelf',
      type: 'fill' as const,
      source: 'openmaptiles',
      'source-layer': 'landcover',
      maxzoom: 8,
      filter: ['all', ['==', '$type', 'Polygon'], ['==', 'subclass', 'ice_shelf']],
      paint: { 'fill-color': 'rgb(12,12,12)', 'fill-opacity': 0.7 },
    },
    {
      id: 'landcover_glacier',
      type: 'fill' as const,
      source: 'openmaptiles',
      'source-layer': 'landcover',
      maxzoom: 8,
      filter: ['all', ['==', '$type', 'Polygon'], ['==', 'subclass', 'glacier']],
      paint: {
        'fill-color': 'hsl(0, 1%, 2%)',
        'fill-opacity': {
          base: 1,
          stops: [
            [0, 1],
            [8, 0.5],
          ],
        },
      },
    },
    {
      id: 'landuse_residential',
      type: 'fill' as const,
      source: 'openmaptiles',
      'source-layer': 'landuse',
      maxzoom: 9,
      filter: ['all', ['==', '$type', 'Polygon'], ['==', 'class', 'residential']],
      paint: { 'fill-color': 'hsl(0, 2%, 5%)', 'fill-opacity': 0.4 },
    },
    {
      id: 'landuse_park',
      type: 'fill' as const,
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['all', ['==', '$type', 'Polygon'], ['==', 'class', 'park']],
      paint: { 'fill-color': 'rgb(32,32,32)' },
    },
    {
      id: 'waterway',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['==', '$type', 'LineString'],
      paint: { 'line-color': 'rgb(27,27,29)' },
    },
    {
      id: 'building',
      type: 'fill' as const,
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 12,
      filter: ['==', '$type', 'Polygon'],
      paint: {
        'fill-antialias': true,
        'fill-color': 'rgb(10,10,10)',
        'fill-outline-color': 'rgb(27,27,29)',
      },
    },
    {
      id: 'aeroway-area',
      type: 'fill' as const,
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      minzoom: 4,
      filter: ['all', ['==', '$type', 'Polygon'], ['in', 'class', 'runway', 'taxiway']],
      paint: { 'fill-color': '#000', 'fill-opacity': 1 },
    },
    {
      id: 'aeroway-runway',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      minzoom: 11,
      filter: ['all', ['in', 'class', 'runway'], ['==', '$type', 'LineString']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#000',
        'line-opacity': 1,
        'line-width': {
          base: 1.5,
          stops: [
            [11, 4],
            [17, 50],
          ],
        },
      },
    },
    {
      id: 'road_pier',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'pier']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': 'rgb(12,12,12)',
        'line-width': {
          base: 1.2,
          stops: [
            [15, 1],
            [17, 4],
          ],
        },
      },
    },
    {
      id: 'highway_path',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'path']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': 'rgb(27,27,29)',
        'line-dasharray': [1.5, 1.5],
        'line-opacity': 0.9,
        'line-width': {
          base: 1.2,
          stops: [
            [13, 1],
            [20, 10],
          ],
        },
      },
    },
    {
      id: 'highway_minor',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'minor', 'service', 'track']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#181818',
        'line-opacity': 0.9,
        'line-width': {
          base: 1.55,
          stops: [
            [13, 1.8],
            [20, 20],
          ],
        },
      },
    },
    {
      id: 'highway_major_casing',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 11,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'primary', 'secondary', 'tertiary', 'trunk'],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': 'rgba(60,60,60,0.8)',
        'line-dasharray': [12, 0],
        'line-width': {
          base: 1.3,
          stops: [
            [10, 3],
            [20, 23],
          ],
        },
      },
    },
    {
      id: 'highway_major_inner',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 11,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'primary', 'secondary', 'tertiary', 'trunk'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': 'hsl(0, 0%, 7%)',
        'line-width': {
          base: 1.3,
          stops: [
            [10, 2],
            [20, 20],
          ],
        },
      },
    },
    {
      id: 'highway_major_subtle',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 6,
      maxzoom: 11,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'primary', 'secondary', 'tertiary', 'trunk'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#2a2a2a',
        'line-width': {
          stops: [
            [6, 0],
            [8, 2],
          ],
        },
      },
    },
    {
      id: 'highway_motorway_casing',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 6,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'motorway']],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': 'rgba(60,60,60,0.8)',
        'line-dasharray': [2, 0],
        'line-opacity': 1,
        'line-width': {
          base: 1.4,
          stops: [
            [5.8, 0],
            [6, 3],
            [20, 40],
          ],
        },
      },
    },
    {
      id: 'highway_motorway_inner',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 6,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'motorway']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': {
          base: 1,
          stops: [
            [5.8, 'hsla(0, 0%, 85%, 0.53)'],
            [6, '#000'],
          ],
        },
        'line-width': {
          base: 1.4,
          stops: [
            [4, 2],
            [6, 1.3],
            [20, 30],
          ],
        },
      },
    },
    {
      id: 'highway_motorway_subtle',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      maxzoom: 6,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'motorway']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#181818',
        'line-width': {
          base: 1.4,
          stops: [
            [4, 2],
            [6, 1.3],
          ],
        },
      },
    },
    {
      id: 'railway',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'rail'], ['!has', 'service']],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': 'rgb(35,35,35)',
        'line-width': {
          base: 1.3,
          stops: [
            [16, 3],
            [20, 7],
          ],
        },
      },
    },
    {
      id: 'railway_dashline',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'rail'], ['!has', 'service']],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': 'rgb(12,12,12)',
        'line-dasharray': [3, 3],
        'line-width': {
          base: 1.3,
          stops: [
            [16, 2],
            [20, 6],
          ],
        },
      },
    },
    {
      id: 'boundary_state',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['==', 'admin_level', 4],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-blur': 0.4,
        'line-color': 'hsl(0, 0%, 21%)',
        'line-dasharray': [2, 2],
        'line-opacity': 1,
        'line-width': {
          base: 1.3,
          stops: [
            [3, 1],
            [22, 15],
          ],
        },
      },
    },
    {
      id: 'boundary_country',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['==', 'admin_level', 2],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-blur': {
          base: 1,
          stops: [
            [0, 0.4],
            [22, 4],
          ],
        },
        'line-color': 'hsl(0, 0%, 23%)',
        'line-opacity': 1,
        'line-width': {
          base: 1.1,
          stops: [
            [3, 1],
            [22, 20],
          ],
        },
      },
    },
    {
      id: 'place_other',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 14,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'class', 'hamlet', 'isolated_dwelling', 'neighbourhood'],
      ],
      layout: {
        'text-anchor': 'center',
        'text-field': '{name:latin}\n{name:nonlatin}',
        'text-font': ['Noto Sans Regular'],
        'text-justify': 'center',
        'text-size': 10,
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': 'rgb(101,101,101)',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(0,0,0,0.7)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_suburb',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 15,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'suburb']],
      layout: {
        'text-anchor': 'center',
        'text-field': '{name:latin}\n{name:nonlatin}',
        'text-font': ['Noto Sans Regular'],
        'text-justify': 'center',
        'text-size': 10,
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': 'rgb(101,101,101)',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(0,0,0,0.7)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_village',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 14,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'village']],
      layout: {
        'text-anchor': 'left',
        'text-field': '{name:latin}\n{name:nonlatin}',
        'text-font': ['Noto Sans Regular'],
        'text-justify': 'left',
        'text-offset': [0.5, 0.2],
        'text-size': 10,
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': 'rgb(101,101,101)',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(0,0,0,0.7)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_town',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 15,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'town']],
      layout: {
        'text-anchor': 'center',
        'text-field': '{name:latin}\n{name:nonlatin}',
        'text-font': ['Noto Sans Regular'],
        'text-justify': 'left',
        'text-size': 10,
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': 'rgb(101,101,101)',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(0,0,0,0.7)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_city',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 14,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'city'], ['>', 'rank', 3]],
      layout: {
        'text-anchor': 'center',
        'text-field': '{name:latin}\n{name:nonlatin}',
        'text-font': ['Noto Sans Regular'],
        'text-justify': 'left',
        'text-size': 10,
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': 'rgb(101,101,101)',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(0,0,0,0.7)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_city_large',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 12,
      filter: ['all', ['==', '$type', 'Point'], ['<=', 'rank', 3], ['==', 'class', 'city']],
      layout: {
        'text-anchor': 'center',
        'text-field': '{name:latin}\n{name:nonlatin}',
        'text-font': ['Noto Sans Regular'],
        'text-justify': 'left',
        'text-size': 14,
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': 'rgb(101,101,101)',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(0,0,0,0.7)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_state',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 12,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'state']],
      layout: {
        'text-field': '{name:latin}\n{name:nonlatin}',
        'text-font': ['Noto Sans Regular'],
        'text-size': 10,
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': 'rgb(101,101,101)',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(0,0,0,0.7)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_country',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 8,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'country']],
      layout: {
        'text-anchor': 'center',
        'text-field': '{name:latin}',
        'text-font': ['Noto Sans Regular'],
        'text-size': {
          base: 1.4,
          stops: [
            [0, 10],
            [3, 12],
            [4, 14],
          ],
        },
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': 'rgb(101,101,101)',
        'text-halo-color': 'rgba(0,0,0,0.7)',
        'text-halo-width': 1.4,
      },
    },
  ],
};
