// Mock for @/theme to avoid react-native-paper ESM import issues
module.exports = {
  colors: {
    primary: '#0D9488',
    background: '#F5F5F5',
    surface: '#FFFFFF',
    textPrimary: '#1A1A1A',
    textSecondary: '#666666',
    border: '#E5E5E5',
    error: '#DC2626',
  },
  darkColors: {
    primary: '#2DD4BF',
    background: '#18181B',
    surface: '#27272A',
    textPrimary: '#FAFAFA',
    textSecondary: '#A1A1AA',
    border: '#3F3F46',
    error: '#F87171',
  },
  brand: {
    teal: '#0D9488',
    gold: '#F59E0B',
  },
  activityTypeColors: {
    Ride: '#3B82F6',
    Run: '#22C55E',
    Swim: '#06B6D4',
    Walk: '#8B5CF6',
    Hike: '#F97316',
    default: '#6B7280',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  layout: {
    borderRadius: 8,
    borderRadiusSm: 4,
    borderRadiusLg: 12,
  },
  typography: {
    title: { fontSize: 28, fontWeight: '600' },
    body: { fontSize: 16, fontWeight: '400' },
    caption: { fontSize: 14, fontWeight: '400' },
  },
  lightTheme: { colors: {} },
  darkTheme: { colors: {} },
  gradients: {},
  glows: {},
  opacity: {},
  zoneColors: {},
  colorWithOpacity: (color, opacity) => color,
  shadows: {},
  createShadow: () => ({}),
  cardShadow: {},
  smallElementShadow: {},
};
