// Generated by uniffi-bindgen-react-native
#include "veloq.h"
// In iOS build, both files are copied to the same ios/cpp/ directory
// In Android build, this file isn't used (Android has its own Kotlin bindings)
#include "tracematch.hpp"

namespace veloq {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeTracematch::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}