// Generated by uniffi-bindgen-react-native
// Note: cpp/veloq.h is included in Veloq.mm, not here, to avoid
// C++ header issues during Objective-C module generation

#import <React/RCTBridgeModule.h>

#ifdef RCT_NEW_ARCH_ENABLED
#import <ReactCommon/RCTTurboModule.h>

// New Architecture: Conform to BOTH protocols
// - RCTBridgeModule is required for RCT_EXPORT_MODULE() macro
// - RCTTurboModule enables the TurboModule system
@interface Veloq : NSObject <RCTBridgeModule, RCTTurboModule>
#else
@interface Veloq : NSObject <RCTBridgeModule>
#endif

@end