// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "veloq.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RouteMatcher.h"

@interface Veloq : NSObject <NativeVeloqSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Veloq : NSObject <RCTBridgeModule>
#endif

@end