export {
  PowerCurveChart,
  PaceCurveChart,
  SwimPaceCurveChart,
  ZoneDistributionChart,
  FTPTrendChart,
  WeeklySummary,
  ActivityHeatmap,
  SeasonComparison,
  DecouplingChart,
} from './components';

export {
  usePaceCurve,
  PACE_CURVE_DISTANCES,
  SWIM_PACE_CURVE_DISTANCES,
  getPaceAtDistance,
  getIndexAtDistance,
  getTimeAtDistance,
  paceToMinPerKm,
  paceToMinPer100m,
  usePowerCurve,
  POWER_CURVE_DURATIONS,
  getPowerAtDuration,
  getIndexAtDuration,
  formatPowerCurveForChart,
  useSeasonBests,
  type BestEffort,
  type UseSeasonBestsResult,
  useScatterGestures,
} from './hooks';

export {
  buildChartData,
  computeAllAverages,
  computeIntervalBands,
  type DataSeries,
  type SeriesInfo,
  type ChartMetricValue,
  type ChartDataResult,
  type IntervalBand,
  detectGaps,
  buildGapCompression,
  calculateChartWidth,
  DEFAULT_GAP_THRESHOLD_DAYS,
  DEFAULT_COMPRESSED_GAP_DAYS,
  type DetectedGap,
  type GapWithPosition,
  type TimeAxisLabel,
  type GapCompressionConfig,
  type GapCompressionResult,
  computeTimeAxisLabels,
  axisLabelsNeedDay,
  formatAxisDate,
  formatShortDateWithYear,
} from './lib';
