// GENERATED by scripts/gen-widget-theme.ts — do not edit. Run: npm run gen:widget-theme
import SwiftUI

/// Static widget palette + metrics. Dynamic colours come from the snapshot `theme`
/// block; this is the placeholder/default chrome before a snapshot lands.
enum WidgetTheme {
  enum Light {
    static let background = Color(hex: "#F8F9FA")
    static let surface = Color(hex: "#FFFFFF")
    static let textPrimary = Color(hex: "#18181B")
    static let textSecondary = Color(hex: "#52525B")
    static let primary = Color(hex: "#0D9488")
    static let gold = Color(hex: "#D4AF37")
    static let blue = Color(hex: "#3A7AB8")
    static let trendUp = Color(hex: "#22C55E")
    static let trendDown = Color(hex: "#52525B")
    static let trendFlat = Color(hex: "#A1A1AA")
    static let border = Color(hex: "#E4E4E7")
  }

  enum Dark {
    static let background = Color(hex: "#0D0D0F")
    static let surface = Color(hex: "#232328")
    static let textPrimary = Color(hex: "#FAFAFA")
    static let textSecondary = Color(hex: "#A1A1AA")
    static let primary = Color(hex: "#2DD4BF")
    static let gold = Color(hex: "#D4AF37")
    static let blue = Color(hex: "#5B9BD5")
    static let trendUp = Color(hex: "#4ADE80")
    static let trendDown = Color(hex: "#A1A1AA")
    static let trendFlat = Color(hex: "#52525B")
    static let border = Color(hex: "#27272A")
  }

  enum Layout {
    static let radius: CGFloat = 16
    static let radiusInner: CGFloat = 8
    static let padding: CGFloat = 16
    static let gap: CGFloat = 8
  }

  enum TypeScale {
    static let hero: CGFloat = 32
    static let metric: CGFloat = 22
    static let value: CGFloat = 18
    static let label: CGFloat = 12
    static let caption: CGFloat = 10
  }
}
