//! Divergence checksums over the shipped migration SQL.
//!
//! `rusqlite_migration` records how many migrations have run, never what they
//! contained, so an edit to an already-applied file is silent. A checked-in
//! hash per file makes it loud.
//!
//! Distinct from `schema_golden.rs`, which compares the resulting schema. An
//! edit that lands on the same final schema, such as reordering two migrations,
//! is invisible there and caught here.
//!
//! Hashing raw bytes, not comment-stripped SQL: stripping needs a real SQL
//! lexer to know a `--` inside a string literal is not a comment, and a
//! hand-rolled stripper that gets that wrong masks real changes silently.

use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

/// Migrations 1..=RELEASED_THROUGH are on user devices today. Every 0.3.0
/// through 0.3.8 build shipped `PRAGMA user_version = 12`, so a live upgrade
/// starts from exactly this prefix having already run.
const RELEASED_THROUGH: usize = 12;

const GOLDEN_REL: &str = "tests/fixtures/migration_checksums.txt";

fn crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn migrations_dir() -> PathBuf {
    crate_root().join("src/migrations")
}

fn golden_path() -> PathBuf {
    crate_root().join(GOLDEN_REL)
}

fn hash_bytes(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

/// Filename -> sha256 of the file's raw bytes, in application order.
fn current_checksums() -> Vec<(String, String)> {
    let mut files: Vec<PathBuf> = fs::read_dir(migrations_dir())
        .expect("read src/migrations")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|e| e == "sql"))
        .collect();
    files.sort();

    assert!(
        !files.is_empty(),
        "no .sql files under {}: the golden would trivially pass against nothing",
        migrations_dir().display()
    );

    files
        .into_iter()
        .map(|p| {
            let name = p.file_name().unwrap().to_string_lossy().to_string();
            let bytes = fs::read(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()));
            (name, hash_bytes(&bytes))
        })
        .collect()
}

fn read_golden() -> Vec<(String, String)> {
    let path = golden_path();
    let text = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read the checksum golden at {}: {e}\n\
             Without it this test has nothing to compare against. Restore it from \
             git, or regenerate with UPDATE_GOLDEN=1 only if you are certain no \
             released migration has been edited.",
            path.display()
        )
    });

    let entries: Vec<(String, String)> = text
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(|l| {
            let (name, hash) = l
                .split_once(char::is_whitespace)
                .unwrap_or_else(|| panic!("malformed golden line: {l:?}"));
            (name.to_string(), hash.trim().to_string())
        })
        .collect();

    assert!(
        !entries.is_empty(),
        "{} parsed to zero entries. An empty golden cannot fail, which defeats \
         the point of having one.",
        path.display()
    );
    entries
}

fn write_golden(entries: &[(String, String)]) {
    let mut out = String::from(
        "# sha256 of each migration SQL file, raw bytes, in application order.\n\
         # Generated by tests/migration_checksums.rs (UPDATE_GOLDEN=1).\n\
         # Append-only: a new migration adds a line. An existing line must never\n\
         # change, because users have already run that file.\n",
    );
    for (name, hash) in entries {
        out.push_str(&format!("{name}  {hash}\n"));
    }
    fs::write(golden_path(), out).expect("write golden");
}

fn released_note(index: usize, name: &str) -> String {
    if index < RELEASED_THROUGH {
        format!(
            "{name} is migration {} of the 1..={RELEASED_THROUGH} prefix that every released \
             0.3.x build already applied. Devices in the field ran the old bytes and will \
             never run the new ones.",
            index + 1
        )
    } else {
        format!(
            "{name} is migration {} and has not shipped yet, so editing it is still safe. \
             Re-bless it now, before release.",
            index + 1
        )
    }
}

#[test]
fn released_migrations_are_immutable() {
    let current = current_checksums();
    let updating = std::env::var("UPDATE_GOLDEN").is_ok_and(|v| v == "1");

    if updating {
        let golden = read_golden();
        let by_name: BTreeMap<&str, &str> = golden
            .iter()
            .map(|(n, h)| (n.as_str(), h.as_str()))
            .collect();

        // The hatch exists for adding a migration, not for re-blessing one that
        // already shipped. Content changes still have to be argued for by hand.
        let changed: Vec<String> = current
            .iter()
            .enumerate()
            .filter_map(|(i, (name, hash))| match by_name.get(name.as_str()) {
                Some(old) if old != hash => Some(released_note(i, name)),
                _ => None,
            })
            .collect();
        assert!(
            changed.is_empty(),
            "UPDATE_GOLDEN=1 adds new migrations, it does not re-bless edited ones.\n{}\n\
             If the edit is genuinely intended, delete the affected line from {GOLDEN_REL} \
             by hand and say why in the commit.",
            changed.join("\n")
        );

        let removed: Vec<&str> = golden
            .iter()
            .map(|(n, _)| n.as_str())
            .filter(|n| !current.iter().any(|(c, _)| c == n))
            .collect();
        assert!(
            removed.is_empty(),
            "UPDATE_GOLDEN=1 would drop migrations that already shipped: {removed:?}. \
             Migrations are append-only."
        );

        write_golden(&current);
        return;
    }

    let golden = read_golden();

    let mut failures: Vec<String> = Vec::new();
    let golden_by_name: BTreeMap<&str, &str> = golden
        .iter()
        .map(|(n, h)| (n.as_str(), h.as_str()))
        .collect();

    for (i, (name, hash)) in current.iter().enumerate() {
        match golden_by_name.get(name.as_str()) {
            Some(expected) if expected == hash => {}
            Some(expected) => failures.push(format!(
                "CONTENT CHANGED: {name}\n  golden  {expected}\n  on disk {hash}\n  {}",
                released_note(i, name)
            )),
            None => failures.push(format!(
                "NOT IN GOLDEN: {name} (sha256 {hash}). If this is a brand new migration, \
                 run UPDATE_GOLDEN=1 to append it."
            )),
        }
    }

    for (name, _) in &golden {
        if !current.iter().any(|(c, _)| c == name) {
            failures.push(format!(
                "MISSING FROM DISK: {name} is in the golden but no longer in src/migrations. \
                 A device that already ran it keeps its effects, so removing it splits the \
                 population in two."
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "\nAn already-released migration changed.\n\n{}\n\n\
         What this means: users who ran the old bytes have a different schema from users \
         who run the new bytes. rusqlite_migration records only a count, so nobody re-runs \
         the edited file and the two populations never converge. The divergence surfaces \
         later as a missing column or a wrong DEFAULT on some devices only.\n\n\
         Fix it forward with a new migration. UPDATE_GOLDEN=1 is for appending a new file, \
         not for making this message go away.\n",
        failures.join("\n\n")
    );
}

/// The golden is only meaningful if it covers the list the engine actually
/// compiles in. A file added to src/migrations but never wired into
/// `migration_scripts()` never runs, and one wired in twice runs twice.
#[test]
fn golden_covers_every_compiled_migration() {
    let scripts = veloqrs::PersistentRouteEngine::migration_scripts();
    let current = current_checksums();

    assert_eq!(
        scripts.len(),
        current.len(),
        "migration_scripts() has {} entries but src/migrations holds {} .sql files. \
         The checksum golden is keyed by filename, so it can only guard files the \
         engine actually applies.",
        scripts.len(),
        current.len()
    );

    for (i, ((name, hash), script)) in current.iter().zip(scripts.iter()).enumerate() {
        assert_eq!(
            &hash_bytes(script.as_bytes()),
            hash,
            "migration slot {} embeds content that is not {name}. Either \
             migration_scripts() is out of order or it include_str!'s a file twice.",
            i + 1
        );
    }
}

/// Guards the constant the failure text leans on. If the released prefix ever
/// moves, this test tells you to move it deliberately.
#[test]
fn released_prefix_matches_the_shipped_user_version() {
    let names: Vec<String> = current_checksums().into_iter().map(|(n, _)| n).collect();
    assert!(
        names.len() >= RELEASED_THROUGH,
        "RELEASED_THROUGH={RELEASED_THROUGH} exceeds the {} migrations on disk",
        names.len()
    );
    assert_eq!(
        names[RELEASED_THROUGH - 1],
        "012_v030.sql",
        "0.3.0 through 0.3.8 all shipped user_version = 12, and 012_v030.sql was the \
         last migration in that build. If the ordering changed, RELEASED_THROUGH is \
         now pointing at the wrong file."
    );
}
