// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "veloqrs.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "Veloq.h"

@interface Veloqrs : NSObject <NativeVeloqrsSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Veloqrs : NSObject <RCTBridgeModule>
#endif

@end