// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "cpp/veloqrs.h"
#endif

#import <React/RCTBridgeModule.h>

#ifdef RCT_NEW_ARCH_ENABLED
#import <ReactCommon/RCTTurboModule.h>

@interface Veloqrs : NSObject <RCTBridgeModule, RCTTurboModule>
#else
@interface Veloqrs : NSObject <RCTBridgeModule>
#endif

@end