# Generated by uniffi-bindgen-react-native
require "json"

package = JSON.parse(File.read(File.join(__dir__, "..", "package.json")))
folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -Wno-comma -Wno-shorten-64-to-32'

Pod::Spec.new do |s|
  s.name         = "Veloqrs"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => min_ios_version_supported }
  s.source       = { :git => "https://github.com/evanjt/veloq", :tag => "#{s.version}" }

  # Source files:
  # *.{h,m,mm} = Veloqrs.h, Veloqrs.mm (TurboModule wrapper) in same directory as podspec
  # Generated/**/*.{swift,h} = UniFFI Swift bindings and FFI headers (generated from Rust)
  # cpp/**/*.{hpp,cpp,h} = C++ entry points generated by uniffi-bindgen-react-native
  s.source_files = "*.{h,m,mm}", "Generated/**/*.{swift,h}", "cpp/**/*.{hpp,cpp,h}"

  # Mark C++ headers as private to prevent Swift from trying to import them
  # (cstdint and C++ namespaces aren't compatible with Objective-C module imports)
  s.private_header_files = "cpp/**/*.{h,hpp}"

  # Note: module_map removed because CocoaPods doesn't support Swift static
  # libraries with custom module maps. The TurboModule is ObjC++ so doesn't need it.
  # If Swift imports are needed later, build as dynamic framework instead.

  # The Rust library is built by a phase of this target, for the SDK and
  # architectures Xcode is building, into the target's own build directory,
  # which the app's library search paths already name. A prebuilt bundle would
  # have its slice names fixed at `pod install` and be linked whatever it held.
  # The phase runs on every build and the builder compiles only when an input
  # changed. The C++ bridge it compiles is copied here first, because
  # `source_files` is matched now and can only name files under this directory.
  builder = File.join(__dir__, "..", "scripts", "build-rust.js")
  unless system("node", builder, "ios", "--sources-only")
    raise "Veloqrs: #{builder} ios --sources-only failed"
  end
  s.script_phase = {
    :name => "Build Rust library",
    :script => '"${PODS_TARGET_SRCROOT}/../scripts/xcode-build-rust.sh" "${PODS_ROOT}/.." "${CONFIGURATION_BUILD_DIR}"',
    :execution_position => :before_compile,
    :output_files => ["${CONFIGURATION_BUILD_DIR}/libveloqrs_ffi.a"],
    :always_out_of_date => "1"
  }

  # The sprite and glyphs the tile scheme handler serves as `veloq-asset/`.
  # `BasemapAssets` is a copy of `../assets/basemap`, which Android packages as
  # its assets, so one set of files feeds both platforms. It is a copy because
  # CocoaPods does not follow a symlink when it lists a bundle's files. The
  # directory is added as a folder, which keeps the `BasemapAssets` prefix
  # inside the bundle; a `**/*` pattern flattens the files into its root.
  syncer = File.join(__dir__, "..", "scripts", "sync-basemap-assets.js")
  unless system("node", syncer)
    raise "Veloqrs: #{syncer} failed"
  end
  s.resource_bundles = { "VeloqBasemap" => ["BasemapAssets"] }

  s.dependency "uniffi-bindgen-react-native"
  # The map's tile scheme handler extends the library's own web view and
  # manager, so this pod compiles against its headers.
  s.dependency "react-native-webview"

  # Base header search paths for cpp headers and Generated headers
  # Include ${PODS_TARGET_SRCROOT} for "cpp/veloqrs.h" includes (avoids case-insensitive conflict with Veloqrs.h)
  base_header_paths = "\"${PODS_TARGET_SRCROOT}\" \"${PODS_TARGET_SRCROOT}/cpp\" \"${PODS_TARGET_SRCROOT}/Generated\""

  # Use install_modules_dependencies helper to install the dependencies if React Native version >=0.71.0.
  if respond_to?(:install_modules_dependencies, true)
    install_modules_dependencies(s)
    # For RN 0.71+, set header search paths
    s.pod_target_xcconfig = {
      "HEADER_SEARCH_PATHS" => base_header_paths,
      "SWIFT_INCLUDE_PATHS" => "\"${PODS_TARGET_SRCROOT}/Generated\"",
      "ENABLE_USER_SCRIPT_SANDBOXING" => "NO"
    }
    # -ObjC ensures the linker loads all ObjC classes, preventing Veloq from being stripped
    # as "unused" (the TurboModule is only accessed via NSClassFromString at runtime)
    # -lveloqrs_ffi explicitly links the Rust library (renamed from libveloqrs.a to avoid
    # case-insensitive conflict with libVeloqrs.a on macOS)
    s.user_target_xcconfig = { "OTHER_LDFLAGS" => "-ObjC -lveloqrs_ffi" }
  else
    s.dependency "React-Core"

    # Don't install the dependencies when we run `pod install` in the old architecture.
    if ENV['RCT_NEW_ARCH_ENABLED'] == '1' then
      s.compiler_flags = folly_compiler_flags + " -DRCT_NEW_ARCH_ENABLED=1"
      s.pod_target_xcconfig = {
          "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/boost\" " + base_header_paths,
          "SWIFT_INCLUDE_PATHS" => "\"${PODS_TARGET_SRCROOT}/Generated\"",
          "OTHER_CPLUSPLUSFLAGS" => "-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1",
          "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
          "ENABLE_USER_SCRIPT_SANDBOXING" => "NO"
      }
      s.dependency "React-Codegen"
      s.dependency "RCT-Folly"
      s.dependency "RCTRequired"
      s.dependency "RCTTypeSafety"
      s.dependency "ReactCommon/turbomodule/core"
    else
      # Old architecture
      s.pod_target_xcconfig = {
        "HEADER_SEARCH_PATHS" => base_header_paths,
        "SWIFT_INCLUDE_PATHS" => "\"${PODS_TARGET_SRCROOT}/Generated\"",
        "ENABLE_USER_SCRIPT_SANDBOXING" => "NO"
      }
    end
  end
end
