/**
 * Scenario: another session has the source or the output of a generated pair
 * half-saved in the shared checkout while a landing runs its drift checks.
 *
 * Expected behaviour: every drift check judges the pair the index holds, so a
 * dirty disk neither fails a clean pair nor hides a stale one.
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

import { gitFreeEnv, runGit } from '../__shared__/gitFixture';

const repo = resolve(__dirname, '../../..');
const SOURCE = 'modules/veloqrs/rust/veloqrs/src/objects/sync.rs';
const OUTPUT = 'src/shared/native/activityWindow.generated.ts';
const rendered = (days: number) =>
  `// Generated by scripts/generate-activity-window.mjs. Do not edit.\nexport const DEFAULT_ACTIVITY_DAYS = ${days};\n`;

function put(root: string, file: string, text: string) {
  mkdirSync(dirname(join(root, file)), { recursive: true });
  writeFileSync(join(root, file), text);
}

function checkout(source: string, output: string): string {
  const root = mkdtempSync(join(tmpdir(), 'drift-index-'));
  runGit(['init', '-q'], root);
  put(root, SOURCE, source);
  put(root, OUTPUT, output);
  runGit(['add', '-A'], root);
  return root;
}

function check(root: string) {
  return spawnSync('node', [join(repo, 'scripts/generate-activity-window.mjs'), '--check'], {
    cwd: root,
    env: gitFreeEnv(),
    encoding: 'utf8',
  });
}

describe('a drift check', () => {
  let root = '';
  afterEach(() => rmSync(root, { recursive: true, force: true }));

  it('passes a clean pair while the disk holds a half-written output', () => {
    root = checkout('const ACTIVITY_DAYS: i64 = 90;\n', rendered(90));
    put(root, OUTPUT, 'export const DEFAULT_ACTIVITY_DAYS = 0; // half saved\n');

    expect(check(root).status).toBe(0);
  });

  it('passes a clean pair while the disk holds a half-edited source', () => {
    root = checkout('const ACTIVITY_DAYS: i64 = 90;\n', rendered(90));
    put(root, SOURCE, 'const ACTIVITY_DAYS: i64 = 30;\n');

    expect(check(root).status).toBe(0);
  });

  it('fails a stale pair in the index even when the disk was fixed', () => {
    root = checkout('const ACTIVITY_DAYS: i64 = 90;\n', rendered(30));
    put(root, OUTPUT, rendered(90));

    expect(check(root).status).not.toBe(0);
  });
});
