/**
 * The sport families, read out of the Rust module that owns them.
 *
 * Seven lists answered "is this cycling" across two languages with memberships
 * of two to nine. The engine is the owner, since five of the seven
 * lived there and two are SQL predicates that cannot be handed to TypeScript,
 * so the TypeScript copy is generated from `sport.rs` and checked rather than
 * written by hand.
 */

/** Rust constant name to the TypeScript key the predicates read. */
const FAMILIES: Record<string, keyof SportTaxonomy> = {
  CYCLING: 'cycling',
  RUNNING: 'running',
  WALKING: 'walking',
  SWIMMING: 'swimming',
  POWER: 'power',
};

export interface SportTaxonomy {
  cycling: readonly string[];
  running: readonly string[];
  walking: readonly string[];
  swimming: readonly string[];
  power: readonly string[];
}

export type SportDisplayGroups = Record<
  'Ride' | 'Run' | 'Swim' | 'Walk' | 'Hike' | 'Snow' | 'Water' | 'Gym' | 'Racket' | 'Other',
  readonly string[]
>;

const DISPLAY_NAMES = [
  'Ride', 'Run', 'Swim', 'Walk', 'Hike', 'Snow', 'Water', 'Gym', 'Racket', 'Other',
] as const;

/** Read each display group from the same Rust constants used by map counts. */
export function readRustSportDisplayGroups(source: string): SportDisplayGroups {
  const families = readRustSportFamilies(source);
  const aliases: Record<string, readonly string[]> = {
    CYCLING: families.cycling,
    RUNNING: families.running,
    SWIMMING: families.swimming,
  };
  const groups: Partial<SportDisplayGroups> = {};
  for (const name of DISPLAY_NAMES) {
    const match = source.match(new RegExp(`pub const DISPLAY_${name.toUpperCase()}: &\\[&str\\] = (?:&\\[([\\s\\S]*?)\\]|([A-Z]+));`));
    if (!match) throw new Error(`sport.rs declares no display group ${name}`);
    const sports = match[2]
      ? aliases[match[2]]
      : [...match[1].matchAll(/"([^"]*)"/g)].map((entry) => entry[1]);
    if (!sports?.length) throw new Error(`display group ${name} names no sport`);
    groups[name] = sports;
  }
  return groups as SportDisplayGroups;
}

/** Read every `pub const NAME: &[&str] = &[...]` the taxonomy declares. */
export function readRustSportFamilies(source: string): SportTaxonomy {
  const taxonomy: Partial<Record<keyof SportTaxonomy, string[]>> = {};
  const declaration = /pub const ([A-Z_]+): &\[&str\] = &\[([\s\S]*?)\];/g;
  for (const match of source.matchAll(declaration)) {
    const key = FAMILIES[match[1]];
    if (!key) continue;
    const sports = [...match[2].matchAll(/"([^"]*)"/g)].map((m) => m[1]);
    if (sports.length === 0) throw new Error(`\`${match[1]}\` names no sport`);
    taxonomy[key] = sports;
  }
  for (const key of Object.values(FAMILIES)) {
    if (!taxonomy[key]) throw new Error(`sport.rs declares no \`${key}\` family`);
  }
  return taxonomy as SportTaxonomy;
}

/** One list as Prettier would print it at 100 columns, so the check never fights the formatter. */
function renderList(name: string, sports: readonly string[]): string[] {
  const quoted = sports.map((s) => `'${s}'`);
  const oneLine = `  ${name}: [${quoted.join(', ')}],`;
  if (oneLine.length <= 100) return [oneLine];
  return [`  ${name}: [`, ...quoted.map((s) => `    ${s},`), '  ],'];
}

/** The generated module, byte for byte. */
export function renderSportTaxonomy(taxonomy: SportTaxonomy, displayGroups: SportDisplayGroups): string {
  const lines = (Object.keys(taxonomy) as (keyof SportTaxonomy)[]).flatMap((name) =>
    renderList(name, taxonomy[name])
  );
  return [
    '// Generated by scripts/generate-sport-taxonomy.ts. Do not edit.',
    '// Source: modules/veloqrs/rust/veloqrs/src/sport.rs. Regenerate with',
    '// `npm run config:sports`.',
    '',
    '/** The sport families, as the engine declares them. */',
    'export const SPORT_FAMILIES = {',
    ...lines,
    '} as const;',
    '',
    '/** The map and settings display groups, as the engine declares them. */',
    'export const SPORT_DISPLAY_GROUPS = {',
    ...DISPLAY_NAMES.flatMap((name) => renderList(name, displayGroups[name])),
    '} as const;',
    '',
  ].join('\n');
}
