/**
 * The trend thresholds, read out of the Rust source that owns them.
 *
 * They were written twice, once in `src/shared/format/trend.ts` as a hand-kept
 * literal and once wherever a verdict was computed in Rust, and nothing checked
 * that they agreed. `trend.ts`'s own header records the drift that caused: the
 * card's baselines were fixed and the widget's were not. Rust is the source, so
 * a verdict it computes and a glyph TypeScript draws read the same table.
 */

/** Which way is better for a metric, or that its direction carries no verdict. */
export type TrendPolarity = 'higher' | 'lower' | 'none';

/** One metric's threshold, its polarity, and the line that explains it. */
export interface TrendMetric {
  name: string;
  deadband: number;
  polarity: TrendPolarity;
  /** The `//` line above the entry, carried across so the reason travels. */
  docs: string | null;
}

/**
 * One entry, however rustfmt has chosen to lay it out: it puts the three fields
 * on one line or on four depending on the width, so the parser reads the block
 * between braces rather than a line.
 */
const ENTRY =
  /TrendMetric\s*\{\s*name:\s*"([A-Za-z]+)"\s*,\s*deadband:\s*([0-9._]+)\s*,\s*polarity:\s*Polarity::(Higher|Lower|None)\s*,?\s*\}/g;

/** The `//` lines immediately above an entry, which carry its reason. */
const LEADING_COMMENT = /(?:^|\n)\s*\/\/\s?([^\n]*)(?=\s*$)/;

/** `1.0` is Rust's spelling of 1, and `0.05` of 0.05. */
function numberFrom(literal: string): number | null {
  const value = Number(literal.replace(/_/g, ''));
  return Number.isFinite(value) ? value : null;
}

/**
 * Read `TREND_METRICS` out of the veloqrs source.
 *
 * Throws rather than returning an empty table: no metric having a threshold
 * reads as every move being a move, on every surface at once, and a generator
 * that writes that silently is worse than one that stops.
 */
export function readRustTrendMetrics(source: string): TrendMetric[] {
  const block = source.match(/pub const TREND_METRICS:[^=]*=\s*&\[([\s\S]*?)\n\];/);
  if (!block) {
    throw new Error('Could not find `pub const TREND_METRICS` in the veloqrs source');
  }

  const metrics: TrendMetric[] = [];
  const body = block[1];
  ENTRY.lastIndex = 0;
  let previousEnd = 0;
  let entry: RegExpExecArray | null;
  while ((entry = ENTRY.exec(body)) !== null) {
    const deadband = numberFrom(entry[2]);
    if (deadband === null) throw new Error(`Could not read a deadband for \`${entry[1]}\``);
    const before = body.slice(previousEnd, entry.index);
    const comment = before.match(LEADING_COMMENT);
    metrics.push({
      name: entry[1],
      deadband,
      polarity: entry[3].toLowerCase() as TrendPolarity,
      docs: comment ? comment[1].trim() : null,
    });
    previousEnd = entry.index + entry[0].length;
  }

  if (metrics.length === 0) {
    throw new Error('`TREND_METRICS` names no metric');
  }
  return metrics;
}

/** The generated module, byte for byte. */
export function renderTrendTable(metrics: TrendMetric[]): string {
  const deadbands = metrics.flatMap((m) => [
    ...(m.docs ? [`  /** ${m.docs} */`] : []),
    `  ${m.name}: ${m.deadband},`,
  ]);
  const polarities = metrics.map((m) => `  ${m.name}: '${m.polarity}',`);
  return [
    '// Generated by scripts/generate-trend-table.ts. Do not edit.',
    '// Source: modules/veloqrs/rust/veloqrs/src/trend_table.rs, `TREND_METRICS`.',
    '// Regenerate with `npm run config:trend`.',
    '',
    '/**',
    ' * How much each metric has to move before it reads as a move at all.',
    ' *',
    " * The units are the metric's own: points of CTL, hours, whole activities,",
    ' * watts, minutes of pace (per kilometre, or per 100 m for CSS), beats,',
    ' * kilograms. Pace is pace, not the critical speed it comes from.',
    ' */',
    'export const TREND_DEADBAND = {',
    ...deadbands,
    '} as const;',
    '',
    '/** A metric with a threshold of its own. */',
    'export type TrendMetric = keyof typeof TREND_DEADBAND;',
    '',
    '/**',
    ' * Which way is better, one entry per metric with a deadband, so a surface',
    ' * never judges a number locally. A pace is minutes per unit distance, so it',
    ' * falls to improve. `none` is a metric with a direction and no judgement: weight,',
    ' * fatigue and form are drawn the way intervals.icu draws them, as a bare arrow',
    " * on the neutral rung, and form's colour is its zone rather than its move.",
    ' */',
    "export const TREND_POLARITY: Record<TrendMetric, 'higher' | 'lower' | 'none'> = {",
    ...polarities,
    '};',
    '',
  ].join('\n');
}
