/**
 * The five numbers the detector is validated at, read out of the Rust source
 * that owns them.
 *
 * They were written twice, once here as a hand-copied literal and once as
 * `SectionConfig::default()`, and nothing checked that they agreed (`C37`).
 * The engine is the source: the flip resets the detector to the Rust default,
 * so a TypeScript copy that drifts advertises numbers nothing is cutting with.
 */

/** The placeholder the settings and preview screens draw before the engine answers. */
export interface UnifiedConfig {
  proximityThreshold: number;
  minSectionLength: number;
  maxSectionLength: number;
  minActivities: number;
  divergenceThreshold: number;
}

/** Rust field name to the TypeScript name the screens read. */
const FIELDS: Record<string, keyof UnifiedConfig> = {
  proximity_threshold: 'proximityThreshold',
  min_section_length: 'minSectionLength',
  max_section_length: 'maxSectionLength',
  min_activities: 'minActivities',
  divergence_threshold: 'divergenceThreshold',
};

/** `200_000.0` is Rust's spelling of 200000, and `2` of 2. */
function numberFrom(literal: string): number | null {
  const value = Number(literal.replace(/_/g, '').replace(/_?f\d\d$/, ''));
  return Number.isFinite(value) ? value : null;
}

/**
 * A field's value is either a literal or a call to a `default_*` helper that
 * returns one, which is how `divergence_threshold` is written.
 */
function resolveValue(expression: string, source: string): number | null {
  const direct = numberFrom(expression);
  if (direct !== null) return direct;

  const call = expression.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*\)$/);
  if (!call) return null;
  const helper = source.match(
    new RegExp(`fn\\s+${call[1]}\\s*\\([^)]*\\)\\s*->[^{]*\\{\\s*([^\\s}]+)\\s*\\}`)
  );
  return helper ? numberFrom(helper[1]) : null;
}

/** Read `impl Default for SectionConfig` out of the tracematch source. */
export function readRustSectionDefaults(source: string): UnifiedConfig {
  const block = source.match(
    /impl\s+Default\s+for\s+SectionConfig\s*\{[\s\S]*?Self\s*\{([\s\S]*?)\n\s*\}/
  );
  if (!block) {
    throw new Error('Could not find `impl Default for SectionConfig` in the tracematch source');
  }

  const config: Partial<UnifiedConfig> = {};
  for (const line of block[1].split('\n')) {
    const field = line.trim().match(/^([a-z_]+)\s*:\s*(.+?),\s*$/);
    if (!field) continue;
    const name = FIELDS[field[1]];
    if (!name) continue;
    const value = resolveValue(field[2], source);
    if (value === null) throw new Error(`Could not read a number for \`${field[1]}\``);
    config[name] = value;
  }

  for (const name of Object.values(FIELDS)) {
    if (config[name] === undefined) {
      throw new Error(`\`impl Default for SectionConfig\` names no ${name}`);
    }
  }
  return config as UnifiedConfig;
}

/** The generated module, byte for byte. */
export function renderUnifiedConfig(config: UnifiedConfig): string {
  const lines = Object.entries(config).map(([name, value]) => `  ${name}: ${value},`);
  return [
    '// Generated by scripts/generate-unified-config.ts. Do not edit.',
    '// Source: modules/veloqrs/rust/tracematch/src/sections/mod.rs,',
    '// `impl Default for SectionConfig`. Regenerate with `npm run config:unified`.',
    '',
    '/** The configuration the detector is validated at, as Rust declares it. */',
    'export const UNIFIED_CONFIG = {',
    ...lines,
    '} as const;',
    '',
  ].join('\n');
}
