/**
 * Generates the committed native widget theme files from the single TS source of
 * truth (`src/shared/theme/widgetTheme.ts`, itself derived from `src/theme/colors.ts`).
 *
 * Widget native code (Swift WidgetKit / Android RemoteViews) cannot import the app
 * theme, so the static chrome it renders before any snapshot exists must read these
 * generated constants. The dynamic, data-driven colours come from the snapshot's
 * `theme` block at render time; these files cover the placeholder/default state.
 *
 * Run: `npm run gen:widget-theme`. The emitted files carry a GENERATED header and must
 * never be hand-edited; change `colors.ts`/`widgetTheme.ts` and regenerate instead.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  widgetLayout,
  widgetPalette,
  widgetRecord,
  widgetType,
  type WidgetPalette,
} from '@/shared/theme/widgetTheme';

const ROOT = join(__dirname, '..');
const GEN = 'GENERATED by scripts/gen-widget-theme.ts. Do not edit. Run: npm run gen:widget-theme';

// Order the palette fields once so Swift and XML stay aligned.
const PALETTE_KEYS: (keyof WidgetPalette)[] = [
  'background',
  'surface',
  'textPrimary',
  'textSecondary',
  'primary',
  'gold',
  'blue',
  'fatigue',
  'chartFitness',
  'chartFatigue',
  'chartCasing',
  'textMuted',
  'formHighRisk',
  'formOptimal',
  'formGreyZone',
  'formFresh',
  'formTransition',
  'trendUp',
  'trendDown',
  'trendFlat',
  'border',
];

const snake = (k: string) => k.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`);

// The palette stores alpha hex as #RRGGBBAA (RN/SwiftUI order); Android XML wants #AARRGGBB.
const androidHex = (hex: string) =>
  hex.length === 9 ? `#${hex.slice(7)}${hex.slice(1, 7)}` : hex;

function swiftPalette(name: string, p: WidgetPalette): string {
  const lines = PALETTE_KEYS.map((k) => `    static let ${k} = Color(hex: "${p[k]}")`);
  return `  enum ${name} {\n${lines.join('\n')}\n  }`;
}

function iosFile(): string {
  return `// ${GEN}
import SwiftUI

/// Static widget palette + metrics. Dynamic colours come from the snapshot \`theme\`
/// block; this is the placeholder/default chrome before a snapshot lands.
enum WidgetTheme {
${swiftPalette('Light', widgetPalette.light)}

${swiftPalette('Dark', widgetPalette.dark)}

  enum Record {
    static let gradientStart = Color(hex: "${widgetRecord.gradientStart}")
    static let gradientEnd = Color(hex: "${widgetRecord.gradientEnd}")
    static let foreground = Color(hex: "${widgetRecord.foreground}")
  }

  enum Layout {
    static let radius: CGFloat = ${widgetLayout.radius}
    static let radiusInner: CGFloat = ${widgetLayout.radiusInner}
    static let padding: CGFloat = ${widgetLayout.padding}
    static let gap: CGFloat = ${widgetLayout.gap}
  }

  enum TypeScale {
    static let hero: CGFloat = ${widgetType.hero}
    static let metric: CGFloat = ${widgetType.metric}
    static let value: CGFloat = ${widgetType.value}
    static let label: CGFloat = ${widgetType.label}
    static let caption: CGFloat = ${widgetType.caption}
  }
}
`;
}

function androidColors(p: WidgetPalette): string {
  return PALETTE_KEYS.map((k) => `  <color name="widget_${snake(k)}">${androidHex(p[k])}</color>`).join(
    '\n'
  );
}

function androidLight(): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GEN} -->
<resources>
${androidColors(widgetPalette.light)}
  <color name="widget_record_grad_start">${widgetRecord.gradientStart}</color>
  <color name="widget_record_grad_end">${widgetRecord.gradientEnd}</color>
  <color name="widget_record_foreground">${widgetRecord.foreground}</color>
  <dimen name="widget_radius">${widgetLayout.radius}dp</dimen>
  <dimen name="widget_radius_inner">${widgetLayout.radiusInner}dp</dimen>
  <dimen name="widget_padding">${widgetLayout.padding}dp</dimen>
  <dimen name="widget_gap">${widgetLayout.gap}dp</dimen>
  <dimen name="widget_text_hero">${widgetType.hero}sp</dimen>
  <dimen name="widget_text_metric">${widgetType.metric}sp</dimen>
  <dimen name="widget_text_value">${widgetType.value}sp</dimen>
  <dimen name="widget_text_label">${widgetType.label}sp</dimen>
  <dimen name="widget_text_caption">${widgetType.caption}sp</dimen>
</resources>
`;
}

function androidNight(): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GEN} -->
<resources>
${androidColors(widgetPalette.dark)}
</resources>
`;
}

function emit(rel: string, contents: string): void {
  const abs = join(ROOT, rel);
  mkdirSync(join(abs, '..'), { recursive: true });
  writeFileSync(abs, contents);
  // eslint-disable-next-line no-console
  console.log(`  wrote ${rel}`);
}

// Canonical tracked location. The config plugins copy these into the prebuilt
// ios/ and android/ projects (both gitignored, regenerated by `expo prebuild`).
emit('widget/ios/VeloqWidget/WidgetTheme.swift', iosFile());
emit('widget/android/res/values/widget_theme.xml', androidLight());
emit('widget/android/res/values-night/widget_theme.xml', androidNight());
// eslint-disable-next-line no-console
console.log('widget theme generated.');
