#!/bin/bash
# Patch uniffi-bindgen-react-native generated files for React Native 0.81+ compatibility
# Run this after: uniffi-bindgen-react-native generate turbo-module ts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
MODULE_DIR="$PROJECT_DIR/modules/route-matcher-native"

echo "Patching generated files for React Native 0.81+ compatibility..."

***REMOVED***
# Patch 1: cpp-adapter.cpp - Fix CallInvokerHolder extraction
# The generated code uses a deprecated approach that doesn't work with RN 0.80+
***REMOVED***
ADAPTER_FILE="$MODULE_DIR/android/cpp-adapter.cpp"

if [ -f "$ADAPTER_FILE" ]; then
    if ! grep -q "jni::static_ref_cast" "$ADAPTER_FILE"; then
        echo "  Patching cpp-adapter.cpp..."
        cat > "$ADAPTER_FILE" << 'EOF'
// Generated by uniffi-bindgen-react-native
// Patched for React Native 0.81+ compatibility (CallInvokerHolder changes)
#include <jni.h>
#include <jsi/jsi.h>
#include <fbjni/fbjni.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "veloq.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;
namespace jni = facebook::jni;

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_veloq_VeloqModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    // Use fbjni to properly extract the CallInvoker from the Java holder object
    // This approach is compatible with React Native 0.76+ (new architecture)
    auto callInvokerHolder = jni::static_ref_cast<react::CallInvokerHolder::javaobject>(
        jni::make_local(callInvokerHolderJavaObj)
    );
    auto jsCallInvoker = callInvokerHolder->cthis()->getCallInvoker();

    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return veloq::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_veloq_VeloqModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return veloq::cleanupRustCrate(*runtime);
}
EOF
    else
        echo "  cpp-adapter.cpp already patched"
    fi
fi

echo "Patching complete!"
