// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "route-matcher-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RouteMatcher.h"

@interface RouteMatcherNative : NSObject <NativeRouteMatcherNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface RouteMatcherNative : NSObject <RCTBridgeModule>
#endif

@end