// Generated by scripts/generate-sport-taxonomy.ts. Do not edit.
// Source: modules/veloqrs/rust/veloqrs/src/sport.rs. Regenerate with
// `npm run config:sports`.

/** The sport families, as the engine declares them. */
export const SPORT_FAMILIES = {
  cycling: [
    'Ride',
    'VirtualRide',
    'MountainBikeRide',
    'GravelRide',
    'EBikeRide',
    'TrackRide',
    'Cyclocross',
    'Handcycle',
    'Velomobile',
  ],
  running: ['Run', 'VirtualRun', 'TrailRun', 'Treadmill'],
  walking: ['Walk', 'Hike'],
  swimming: ['Swim', 'OpenWaterSwim'],
  power: [
    'Ride',
    'VirtualRide',
    'MountainBikeRide',
    'GravelRide',
    'EBikeRide',
    'TrackRide',
    'Cyclocross',
    'Handcycle',
    'Velomobile',
    'Rowing',
    'VirtualRow',
  ],
} as const;
