// Generated by scripts/generate-sport-taxonomy.ts. Do not edit.
// Source: modules/veloqrs/rust/veloqrs/src/sport.rs. Regenerate with
// `npm run config:sports`.

/** The sport families, as the engine declares them. */
export const SPORT_FAMILIES = {
  cycling: [
    'Ride',
    'VirtualRide',
    'MountainBikeRide',
    'GravelRide',
    'EBikeRide',
    'TrackRide',
    'Cyclocross',
    'Handcycle',
    'Velomobile',
  ],
  running: ['Run', 'VirtualRun', 'TrailRun', 'Treadmill'],
  walking: ['Walk', 'Hike'],
  swimming: ['Swim', 'OpenWaterSwim'],
  power: [
    'Ride',
    'VirtualRide',
    'MountainBikeRide',
    'GravelRide',
    'EBikeRide',
    'TrackRide',
    'Cyclocross',
    'Handcycle',
    'Velomobile',
    'Rowing',
    'VirtualRow',
  ],
} as const;

/** The map and settings display groups, as the engine declares them. */
export const SPORT_DISPLAY_GROUPS = {
  Ride: [
    'Ride',
    'VirtualRide',
    'MountainBikeRide',
    'GravelRide',
    'EBikeRide',
    'TrackRide',
    'Cyclocross',
    'Handcycle',
    'Velomobile',
  ],
  Run: ['Run', 'VirtualRun', 'TrailRun', 'Treadmill'],
  Swim: ['Swim', 'OpenWaterSwim'],
  Walk: ['Walk'],
  Hike: ['Hike', 'Snowshoe'],
  Snow: ['AlpineSki', 'NordicSki', 'BackcountrySki', 'Snowboard', 'RollerSki'],
  Water: [
    'Rowing',
    'VirtualRow',
    'Kayaking',
    'Canoeing',
    'Surfing',
    'Kitesurf',
    'Windsurf',
    'StandUpPaddling',
    'Sail',
  ],
  Gym: [
    'Workout',
    'WeightTraining',
    'Yoga',
    'Pilates',
    'Crossfit',
    'Elliptical',
    'StairStepper',
    'HighIntensityIntervalTraining',
    'IceSkate',
    'InlineSkate',
    'Skateboard',
  ],
  Racket: ['Tennis', 'Badminton', 'Pickleball', 'Racquetball', 'Squash', 'TableTennis'],
  Other: ['Soccer', 'Golf', 'RockClimbing', 'Wheelchair', 'Other'],
} as const;
