// Generated by scripts/generate-unified-config.ts. Do not edit.
// Source: modules/veloqrs/rust/tracematch/src/sections/mod.rs,
// `impl Default for SectionConfig`. Regenerate with `npm run config:unified`.

/** The configuration the detector is validated at, as Rust declares it. */
export const UNIFIED_CONFIG = {
  proximityThreshold: 200,
  minSectionLength: 150,
  maxSectionLength: 200000,
  minActivities: 2,
  divergenceThreshold: 0.15,
} as const;
