/**
 * Manages heatmap tile lifecycle: generation, invalidation, and serving.
 *
 * Tiles are generated by Rust as PNGs at `{documentDirectory}/heatmap-tiles/{z}/{x}/{y}.png`
 * and served to MapLibre via a `file://` URL template.
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import * as FileSystem from 'expo-file-system/legacy';
import { InteractionManager } from 'react-native';
import { getRouteEngine } from '@/lib/native/routeEngine';

const HEATMAP_DIR = `${FileSystem.documentDirectory}heatmap-tiles/`;
const MIN_ZOOM = 8;
const MAX_ZOOM = 15;

/** Debounce delay for viewport-triggered generation (ms).
 * Set above the 500ms camera fitBounds animation to avoid blocking it. */
const VIEWPORT_DEBOUNCE_MS = 800;

export interface UseHeatmapTilesResult {
  /** file:// URL template for MapLibre RasterSource */
  tileUrlTemplate: string;
  /** Whether any tiles exist on disk */
  tilesReady: boolean;
  /** Whether tile generation is currently running */
  isGenerating: boolean;
  /** Generate tiles for a viewport. Debounced internally. */
  generateForViewport: (bounds: {
    minLat: number;
    maxLat: number;
    minLng: number;
    maxLng: number;
  }) => void;
  /** Invalidate tiles that overlap with new activity bounds */
  invalidateForBounds: (bounds: {
    minLat: number;
    maxLat: number;
    minLng: number;
    maxLng: number;
  }) => void;
  /** Clear all heatmap tiles from disk */
  clearAllTiles: () => void;
}

export function useHeatmapTiles(options?: { enabled?: boolean }): UseHeatmapTilesResult {
  const enabled = options?.enabled ?? true;
  const [tilesReady, setTilesReady] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const debounceTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const mountedRef = useRef(true);

  const tileUrlTemplate = `file://${HEATMAP_DIR}{z}/{x}/{y}.png`;

  // Check if tiles directory exists on mount
  useEffect(() => {
    mountedRef.current = true;
    if (!enabled) return;

    FileSystem.getInfoAsync(HEATMAP_DIR).then((info) => {
      if (mountedRef.current) {
        setTilesReady(info.exists);
      }
    });

    return () => {
      mountedRef.current = false;
      if (debounceTimer.current) clearTimeout(debounceTimer.current);
    };
  }, [enabled]);

  // Subscribe to engine activity events for auto-invalidation
  useEffect(() => {
    if (!enabled) return;

    const engine = getRouteEngine();
    if (!engine) return;

    const unsubscribe = engine.subscribe('syncReset', () => {
      // Full sync reset: clear all tiles
      engine.clearHeatmapTiles(HEATMAP_DIR);
      if (mountedRef.current) setTilesReady(false);
    });

    return unsubscribe;
  }, [enabled]);

  const generateForViewport = useCallback(
    (bounds: { minLat: number; maxLat: number; minLng: number; maxLng: number }) => {
      if (!enabled) return;
      if (debounceTimer.current) clearTimeout(debounceTimer.current);

      debounceTimer.current = setTimeout(() => {
        InteractionManager.runAfterInteractions(() => {
          if (!mountedRef.current) return;
          const engine = getRouteEngine();
          if (!engine) return;

          setIsGenerating(true);
          try {
            engine.generateHeatmapTiles(
              HEATMAP_DIR,
              bounds.minLat,
              bounds.maxLat,
              bounds.minLng,
              bounds.maxLng,
              MIN_ZOOM,
              MAX_ZOOM
            );
            if (mountedRef.current) {
              setTilesReady(true);
              setIsGenerating(false);
            }
          } catch {
            if (mountedRef.current) setIsGenerating(false);
          }
        });
      }, VIEWPORT_DEBOUNCE_MS);
    },
    [enabled]
  );

  const invalidateForBounds = useCallback(
    (bounds: { minLat: number; maxLat: number; minLng: number; maxLng: number }) => {
      if (!enabled) return;
      const engine = getRouteEngine();
      if (!engine) return;
      engine.invalidateHeatmapTiles(
        HEATMAP_DIR,
        bounds.minLat,
        bounds.maxLat,
        bounds.minLng,
        bounds.maxLng
      );
    },
    [enabled]
  );

  const clearAllTiles = useCallback(() => {
    const engine = getRouteEngine();
    if (engine) {
      engine.clearHeatmapTiles(HEATMAP_DIR);
    }
    if (mountedRef.current) setTilesReady(false);
  }, []);

  return {
    tileUrlTemplate,
    tilesReady,
    isGenerating,
    generateForViewport,
    invalidateForBounds,
    clearAllTiles,
  };
}

/** The base directory where heatmap tiles are stored */
export const HEATMAP_TILES_DIR = HEATMAP_DIR;
