export const LIBERTY_LAYERS_BRIDGE = [
  // --- Bridges ---
  {
    id: 'bridge_motorway_link_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'class'], 'motorway'],
      ['==', ['get', 'ramp'], 1],
      ['==', ['get', 'brunnel'], 'bridge'],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 12, 1, 13, 3, 14, 4, 20, 15],
    },
  },
  {
    id: 'bridge_service_track_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['service', 'track'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#cfcdca',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15, 1, 16, 4, 20, 11],
    },
  },
  {
    id: 'bridge_link_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'class'], 'link'], ['==', ['get', 'brunnel'], 'bridge']],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 12, 1, 13, 3, 14, 4, 20, 15],
    },
  },
  {
    id: 'bridge_street_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['street', 'street_limited'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': 'hsl(36,6%,74%)',
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 12, 0, 12.5, 1],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 12, 0.5, 13, 1, 14, 4, 20, 25],
    },
  },
  {
    id: 'bridge_path_pedestrian_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['path', 'pedestrian'], true, false],
    ],
    paint: {
      'line-color': 'hsl(35,6%,80%)',
      'line-dasharray': [1, 0],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 14, 1.5, 20, 18],
    },
  },
  {
    id: 'bridge_secondary_tertiary_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['secondary', 'tertiary'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 8, 1.5, 20, 17],
    },
  },
  {
    id: 'bridge_trunk_primary_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['primary', 'trunk'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        5,
        0.4,
        6,
        0.7,
        7,
        1.75,
        20,
        22,
      ],
    },
  },
  {
    id: 'bridge_motorway_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'class'], 'motorway'],
      ['!=', ['get', 'ramp'], 1],
      ['==', ['get', 'brunnel'], 'bridge'],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        5,
        0.4,
        6,
        0.7,
        7,
        1.75,
        20,
        22,
      ],
    },
  },
  {
    id: 'bridge_path_pedestrian',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['path', 'pedestrian'], true, false],
    ],
    paint: {
      'line-color': 'hsl(0,0%,100%)',
      'line-dasharray': [1, 0.3],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 14, 0.5, 20, 10],
    },
  },
  {
    id: 'bridge_motorway_link',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'class'], 'motorway'],
      ['==', ['get', 'ramp'], 1],
      ['==', ['get', 'brunnel'], 'bridge'],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fc8',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        12.5,
        0,
        13,
        1.5,
        14,
        2.5,
        20,
        11.5,
      ],
    },
  },
  {
    id: 'bridge_service_track',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['service', 'track'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fff',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15.5, 0, 16, 2, 20, 7.5],
    },
  },
  {
    id: 'bridge_link',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'class'], 'link'], ['==', ['get', 'brunnel'], 'bridge']],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fea',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        12.5,
        0,
        13,
        1.5,
        14,
        2.5,
        20,
        11.5,
      ],
    },
  },
  {
    id: 'bridge_street',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['minor'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fff',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 13.5, 0, 14, 2.5, 20, 18],
    },
  },
  {
    id: 'bridge_secondary_tertiary',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['secondary', 'tertiary'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fea',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 6.5, 0, 7, 0.5, 20, 10],
    },
  },
  {
    id: 'bridge_trunk_primary',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'bridge'],
      ['match', ['get', 'class'], ['primary', 'trunk'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fea',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
    },
  },
  {
    id: 'bridge_motorway',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'class'], 'motorway'],
      ['!=', ['get', 'ramp'], 1],
      ['==', ['get', 'brunnel'], 'bridge'],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fc8',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
    },
  },
  {
    id: 'bridge_major_rail',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'class'], 'rail'], ['==', ['get', 'brunnel'], 'bridge']],
    paint: {
      'line-color': '#bbb',
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
    },
  },
  {
    id: 'bridge_major_rail_hatching',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'class'], 'rail'], ['==', ['get', 'brunnel'], 'bridge']],
    paint: {
      'line-color': '#bbb',
      'line-dasharray': [0.2, 8],
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14.5, 0, 15, 3, 20, 8],
    },
  },
  {
    id: 'bridge_transit_rail',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'class'], 'transit'], ['==', ['get', 'brunnel'], 'bridge']],
    paint: {
      'line-color': '#bbb',
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
    },
  },
  {
    id: 'bridge_transit_rail_hatching',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'class'], 'transit'], ['==', ['get', 'brunnel'], 'bridge']],
    paint: {
      'line-color': '#bbb',
      'line-dasharray': [0.2, 8],
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14.5, 0, 15, 3, 20, 8],
    },
  },
] as const;
