export const LIBERTY_LAYERS_ROAD = [
  // --- Tunnels ---
  {
    id: 'tunnel_motorway_link_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'class'], 'motorway'],
      ['==', ['get', 'ramp'], 1],
      ['==', ['get', 'brunnel'], 'tunnel'],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-dasharray': [0.5, 0.25],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 12, 1, 13, 3, 14, 4, 20, 15],
    },
  },
  {
    id: 'tunnel_service_track_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['service', 'track'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#cfcdca',
      'line-dasharray': [0.5, 0.25],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15, 1, 16, 4, 20, 11],
    },
  },
  {
    id: 'tunnel_link_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'ramp'], 1], ['==', ['get', 'brunnel'], 'tunnel']],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 12, 1, 13, 3, 14, 4, 20, 15],
    },
  },
  {
    id: 'tunnel_street_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['street', 'street_limited'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#cfcdca',
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 12, 0, 12.5, 1],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 12, 0.5, 13, 1, 14, 4, 20, 15],
    },
  },
  {
    id: 'tunnel_secondary_tertiary_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['secondary', 'tertiary'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 8, 1.5, 20, 17],
    },
  },
  {
    id: 'tunnel_trunk_primary_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['primary', 'trunk'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        5,
        0.4,
        6,
        0.7,
        7,
        1.75,
        20,
        22,
      ],
    },
  },
  {
    id: 'tunnel_motorway_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'class'], 'motorway'],
      ['!=', ['get', 'ramp'], 1],
      ['==', ['get', 'brunnel'], 'tunnel'],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-dasharray': [0.5, 0.25],
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        5,
        0.4,
        6,
        0.7,
        7,
        1.75,
        20,
        22,
      ],
    },
  },
  {
    id: 'tunnel_path_pedestrian',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['path', 'pedestrian'], true, false],
    ],
    paint: {
      'line-color': 'hsl(0,0%,100%)',
      'line-dasharray': [1, 0.75],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 14, 0.5, 20, 10],
    },
  },
  {
    id: 'tunnel_motorway_link',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'class'], 'motorway'],
      ['==', ['get', 'ramp'], 1],
      ['==', ['get', 'brunnel'], 'tunnel'],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fc8',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        12.5,
        0,
        13,
        1.5,
        14,
        2.5,
        20,
        11.5,
      ],
    },
  },
  {
    id: 'tunnel_service_track',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['service', 'track'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fff',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15.5, 0, 16, 2, 20, 7.5],
    },
  },
  {
    id: 'tunnel_link',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'ramp'], 1], ['==', ['get', 'brunnel'], 'tunnel']],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fff4c6',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        12.5,
        0,
        13,
        1.5,
        14,
        2.5,
        20,
        11.5,
      ],
    },
  },
  {
    id: 'tunnel_minor',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['minor'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fff',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 13.5, 0, 14, 2.5, 20, 11.5],
    },
  },
  {
    id: 'tunnel_secondary_tertiary',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['secondary', 'tertiary'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fff4c6',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 6.5, 0, 7, 0.5, 20, 10],
    },
  },
  {
    id: 'tunnel_trunk_primary',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['primary', 'trunk'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fff4c6',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
    },
  },
  {
    id: 'tunnel_motorway',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'class'], 'motorway'],
      ['!=', ['get', 'ramp'], 1],
      ['==', ['get', 'brunnel'], 'tunnel'],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#ffdaa6',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
    },
  },
  {
    id: 'tunnel_major_rail',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['rail'], true, false],
    ],
    paint: {
      'line-color': '#bbb',
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
    },
  },
  {
    id: 'tunnel_major_rail_hatching',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'brunnel'], 'tunnel'], ['==', ['get', 'class'], 'rail']],
    paint: {
      'line-color': '#bbb',
      'line-dasharray': [0.2, 8],
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14.5, 0, 15, 3, 20, 8],
    },
  },
  {
    id: 'tunnel_transit_rail',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['==', ['get', 'brunnel'], 'tunnel'],
      ['match', ['get', 'class'], ['transit'], true, false],
    ],
    paint: {
      'line-color': '#bbb',
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
    },
  },
  {
    id: 'tunnel_transit_rail_hatching',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['all', ['==', ['get', 'brunnel'], 'tunnel'], ['==', ['get', 'class'], 'transit']],
    paint: {
      'line-color': '#bbb',
      'line-dasharray': [0.2, 8],
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14.5, 0, 15, 3, 20, 8],
    },
  },
  // --- Roads ---
  {
    id: 'road_area_pattern',
    type: 'fill' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: ['match', ['geometry-type'], ['MultiPolygon', 'Polygon'], true, false],
    paint: { 'fill-pattern': 'pedestrian_polygon' },
  },
  {
    id: 'road_motorway_link_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    minzoom: 12,
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['==', ['get', 'class'], 'motorway'],
      ['==', ['get', 'ramp'], 1],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 12, 1, 13, 3, 14, 4, 20, 15],
    },
  },
  {
    id: 'road_service_track_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['match', ['get', 'class'], ['service', 'track'], true, false],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#cfcdca',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15, 1, 16, 4, 20, 11],
    },
  },
  {
    id: 'road_link_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    minzoom: 13,
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      [
        'match',
        ['get', 'class'],
        ['motorway', 'path', 'pedestrian', 'service', 'track'],
        false,
        true,
      ],
      ['==', ['get', 'ramp'], 1],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 12, 1, 13, 3, 14, 4, 20, 15],
    },
  },
  {
    id: 'road_minor_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['match', ['get', 'class'], ['minor'], true, false],
      ['!=', ['get', 'ramp'], 1],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#cfcdca',
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 12, 0, 12.5, 1],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 12, 0.5, 13, 1, 14, 4, 20, 20],
    },
  },
  {
    id: 'road_secondary_tertiary_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['match', ['get', 'class'], ['secondary', 'tertiary'], true, false],
      ['!=', ['get', 'ramp'], 1],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 8, 1.5, 20, 17],
    },
  },
  {
    id: 'road_trunk_primary_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['match', ['get', 'class'], ['primary', 'trunk'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        5,
        0.4,
        6,
        0.7,
        7,
        1.75,
        20,
        22,
      ],
    },
  },
  {
    id: 'road_motorway_casing',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    minzoom: 5,
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['==', ['get', 'class'], 'motorway'],
      ['!=', ['get', 'ramp'], 1],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#e9ac77',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        5,
        0.4,
        6,
        0.7,
        7,
        1.75,
        20,
        22,
      ],
    },
  },
  {
    id: 'road_path_pedestrian',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    minzoom: 14,
    filter: [
      'all',
      ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['match', ['get', 'class'], ['path', 'pedestrian'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': 'hsl(0,0%,100%)',
      'line-dasharray': [1, 0.7],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 14, 1, 20, 10],
    },
  },
  {
    id: 'road_motorway_link',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    minzoom: 12,
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['==', ['get', 'class'], 'motorway'],
      ['==', ['get', 'ramp'], 1],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#fc8',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        12.5,
        0,
        13,
        1.5,
        14,
        2.5,
        20,
        11.5,
      ],
    },
  },
  {
    id: 'road_service_track',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['match', ['get', 'class'], ['service', 'track'], true, false],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#fff',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15.5, 0, 16, 2, 20, 7.5],
    },
  },
  {
    id: 'road_link',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    minzoom: 13,
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['==', ['get', 'ramp'], 1],
      [
        'match',
        ['get', 'class'],
        ['motorway', 'path', 'pedestrian', 'service', 'track'],
        false,
        true,
      ],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#fea',
      'line-width': [
        'interpolate',
        ['exponential', 1.2],
        ['zoom'],
        12.5,
        0,
        13,
        1.5,
        14,
        2.5,
        20,
        11.5,
      ],
    },
  },
  {
    id: 'road_minor',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['match', ['get', 'class'], ['minor'], true, false],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#fff',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 13.5, 0, 14, 2.5, 20, 18],
    },
  },
  {
    id: 'road_secondary_tertiary',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['match', ['get', 'class'], ['secondary', 'tertiary'], true, false],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#fea',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 6.5, 0, 8, 0.5, 20, 13],
    },
  },
  {
    id: 'road_trunk_primary',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['match', ['get', 'class'], ['primary', 'trunk'], true, false],
    ],
    layout: { 'line-join': 'round' },
    paint: {
      'line-color': '#fea',
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
    },
  },
  {
    id: 'road_motorway',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    minzoom: 5,
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['==', ['get', 'class'], 'motorway'],
      ['!=', ['get', 'ramp'], 1],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': ['interpolate', ['linear'], ['zoom'], 5, 'hsl(26,87%,62%)', 6, '#fc8'],
      'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
    },
  },
  {
    id: 'road_major_rail',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['==', ['get', 'class'], 'rail'],
    ],
    paint: {
      'line-color': '#bbb',
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
    },
  },
  {
    id: 'road_major_rail_hatching',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['==', ['get', 'class'], 'rail'],
    ],
    paint: {
      'line-color': '#bbb',
      'line-dasharray': [0.2, 8],
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14.5, 0, 15, 3, 20, 8],
    },
  },
  {
    id: 'road_transit_rail',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['==', ['get', 'class'], 'transit'],
    ],
    paint: {
      'line-color': '#bbb',
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
    },
  },
  {
    id: 'road_transit_rail_hatching',
    type: 'line' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    filter: [
      'all',
      ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
      ['==', ['get', 'class'], 'transit'],
    ],
    paint: {
      'line-color': '#bbb',
      'line-dasharray': [0.2, 8],
      'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14.5, 0, 15, 3, 20, 8],
    },
  },
  {
    id: 'road_one_way_arrow',
    type: 'symbol' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    minzoom: 16,
    filter: ['==', ['get', 'oneway'], 1],
    layout: { 'icon-image': 'arrow', 'symbol-placement': 'line' },
  },
  {
    id: 'road_one_way_arrow_opposite',
    type: 'symbol' as const,
    source: 'openmaptiles',
    'source-layer': 'transportation',
    minzoom: 16,
    filter: ['==', ['get', 'oneway'], -1],
    layout: { 'icon-image': 'arrow', 'icon-rotate': 180, 'symbol-placement': 'line' },
  },
] as const;
