#ifndef ROUTEMATCHERNATIVE_H
#define ROUTEMATCHERNATIVE_H
// Generated by uniffi-bindgen-react-native
#include <ReactCommon/CallInvoker.h>
#include <cstdint>
#include <jsi/jsi.h>

namespace routematchernative {
using namespace facebook;

uint8_t installRustCrate(jsi::Runtime &runtime,
                         std::shared_ptr<react::CallInvoker> callInvoker);
uint8_t cleanupRustCrate(jsi::Runtime &runtime);
} // namespace routematchernative

#endif /* ROUTEMATCHERNATIVE_H */