// Generated by uniffi-bindgen-react-native
#include "veloq.h"
#include "../modules/route-matcher-native/cpp/tracematch.hpp"

namespace veloq {
using namespace facebook;

uint8_t installRustCrate(jsi::Runtime &runtime,
                         std::shared_ptr<react::CallInvoker> callInvoker) {
  NativeTracematch::registerModule(runtime, callInvoker);
  return true;
}

uint8_t cleanupRustCrate(jsi::Runtime &runtime) { return false; }
} // namespace veloq