/**
 * Scenario: tracematch is a workspace member here, so cargo in this checkout
 * writes the workspace lockfile and never tracematch's own `Cargo.lock`. A
 * version bump in `tracematch/Cargo.toml` passes every local gate and leaves the
 * standalone lockfile naming the old version, which only tracematch's CI finds,
 * at `cargo publish --locked`, after a push that can be weeks away.
 *
 * Expected behaviour: a guard that fails, naming both versions, when the
 * `[[package]]` entry named tracematch in the standalone lockfile differs from
 * the manifest's `[package]` version, and stays quiet when the submodule is not
 * checked out, which is every fresh worktree until the clone recipe runs.
 */

import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const SCRIPT = join(__dirname, '../../../scripts/lint-tracematch-lockfile.mjs');
const SUB = 'modules/veloqrs/rust/tracematch';

function runGuard(root: string): { status: number; output: string } {
  try {
    const output = execFileSync('node', [SCRIPT, '--root', root], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return { status: 0, output };
  } catch (error) {
    const e = error as { status: number; stdout?: string; stderr?: string };
    return { status: e.status, output: `${e.stdout ?? ''}${e.stderr ?? ''}` };
  }
}

const roots: string[] = [];

function checkout(): string {
  const root = mkdtempSync(join(tmpdir(), 'tm-lockfile-'));
  roots.push(root);
  return root;
}

// A dependency table after `[package]` carries its own `version` keys, and a
// neighbouring package in the lockfile has a name that starts the same way, so
// a guard reading the first `version` it meets gets the wrong answer.
function manifest(version: string): string {
  return [
    '[package]',
    'name = "tracematch"',
    `version = "${version}"`,
    'edition = "2024"',
    '',
    '[dependencies]',
    'serde = { version = "1.0", features = ["derive"] }',
    '',
  ].join('\n');
}

function lockfile(version: string | null): string {
  const entries = [
    '# This file is automatically @generated by Cargo.',
    'version = 4',
    '',
    '[[package]]',
    'name = "serde"',
    'version = "1.0.228"',
    '',
    '[[package]]',
    'name = "tracematch-derive"',
    'version = "0.9.0"',
    '',
  ];
  if (version !== null) {
    entries.push(
      '[[package]]',
      'name = "tracematch"',
      `version = "${version}"`,
      'dependencies = [',
      ' "serde",',
      ']',
      ''
    );
  }
  return entries.join('\n');
}

function withSubmodule(manifestVersion: string, lockVersion: string | null | undefined): string {
  const root = checkout();
  const dir = join(root, SUB);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'Cargo.toml'), manifest(manifestVersion));
  if (lockVersion !== undefined) writeFileSync(join(dir, 'Cargo.lock'), lockfile(lockVersion));
  return root;
}

afterAll(() => {
  for (const root of roots) rmSync(root, { recursive: true, force: true });
});

describe('lint-tracematch-lockfile', () => {
  it('passes when the lockfile names the manifest version', () => {
    expect(runGuard(withSubmodule('3.0.0', '3.0.0')).status).toBe(0);
  });

  it('fails naming both versions when the lockfile is stale', () => {
    const r = runGuard(withSubmodule('3.1.0', '3.0.0'));
    expect(r.status).toBe(1);
    expect(r.output).toContain('3.1.0');
    expect(r.output).toContain('3.0.0');
  });

  it('fails when the lockfile carries no tracematch entry at all', () => {
    const r = runGuard(withSubmodule('3.0.0', null));
    expect(r.status).toBe(1);
    expect(r.output).toContain('3.0.0');
  });

  it('fails when the manifest is checked out and the lockfile is missing', () => {
    const r = runGuard(withSubmodule('3.0.0', undefined));
    expect(r.status).toBe(1);
    expect(r.output).toContain('Cargo.lock');
  });

  it('passes when the submodule directory is absent', () => {
    expect(runGuard(checkout()).status).toBe(0);
  });

  it('passes when the submodule directory is empty, as a fresh worktree has it', () => {
    const root = checkout();
    mkdirSync(join(root, SUB), { recursive: true });
    expect(runGuard(root).status).toBe(0);
  });
});
