// Generated by uniffi-bindgen-react-native
// Modified to use NativeModules for RN 0.81+ compatibility
import { NativeModules } from 'react-native';

export interface Spec {
  installRustCrate(): boolean;
  cleanupRustCrate(): boolean;
}

const { Veloq } = NativeModules;

if (!Veloq) {
  throw new Error('NativeModules.Veloq is null. Make sure the native module is properly linked.');
}

export default Veloq as Spec;
