#!/bin/bash
# Clean build artifacts for rebuild
# Usage: ./scripts/clean.sh          (preserves rust/target/ and bindings for fast incremental rebuilds)
#        ./scripts/clean.sh --full   (removes everything including rust/target/ and generated bindings)
#        npm run clean (from modules/veloqrs)

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MODULE_DIR="$(dirname "$SCRIPT_DIR")"

FULL=false
if [ "$1" = "--full" ]; then
  FULL=true
fi

echo "🧹 Cleaning veloqrs build artifacts..."

# Rust build cache (only with --full flag)
if [ "$FULL" = true ] && [ -d "$MODULE_DIR/rust/target" ]; then
  echo "  Removing rust/target/"
  rm -rf "$MODULE_DIR/rust/target"
fi

# Android jniLibs left by builds that wrote the library into the source tree
if [ -d "$MODULE_DIR/android/src/main/jniLibs" ]; then
  echo "  Removing android/src/main/jniLibs/"
  rm -rf "$MODULE_DIR/android/src/main/jniLibs"
fi

# Android Gradle build output
if [ -d "$MODULE_DIR/android/build" ]; then
  echo "  Removing android/build/"
  rm -rf "$MODULE_DIR/android/build"
fi

# Android CMake build cache
if [ -d "$MODULE_DIR/android/.cxx" ]; then
  echo "  Removing android/.cxx/"
  rm -rf "$MODULE_DIR/android/.cxx"
fi

# Generated bindings (only with --full flag; they are committed and regenerated by npm run ffi:generate)
if [ "$FULL" = true ]; then
  if [ -d "$MODULE_DIR/src/generated" ]; then
    echo "  Removing src/generated/"
    rm -rf "$MODULE_DIR/src/generated"
  fi

  if [ -d "$MODULE_DIR/android/generated" ]; then
    echo "  Removing android/generated/"
    rm -rf "$MODULE_DIR/android/generated"
  fi

  if [ -d "$MODULE_DIR/cpp/generated" ]; then
    echo "  Removing cpp/generated/"
    rm -rf "$MODULE_DIR/cpp/generated"
  fi
fi

# iOS build artifacts
if [ -d "$MODULE_DIR/ios/Frameworks" ]; then
  echo "  Removing ios/Frameworks/"
  rm -rf "$MODULE_DIR/ios/Frameworks"
fi

if [ -d "$MODULE_DIR/ios/cpp" ]; then
  echo "  Removing ios/cpp/"
  rm -rf "$MODULE_DIR/ios/cpp"
fi

if [ -d "$MODULE_DIR/ios/build" ]; then
  echo "  Removing ios/build/"
  rm -rf "$MODULE_DIR/ios/build"
fi

# Rust library outputs and their manifests (forces a rebuild on next build)
if [ -d "$MODULE_DIR/build" ]; then
  echo "  Removing build/"
  rm -rf "$MODULE_DIR/build"
fi

# Freshness markers an earlier build wrote beside the module
rm -f "$MODULE_DIR/.rust-source-hash" "$MODULE_DIR"/.rust-build-*

# iOS: the xcframework Xcode actually links lives in DerivedData, not the repo.
# Clearing ios/Frameworks above leaves a stale copy that relinks against the old
# .a (undefined-symbol errors), so remove the DerivedData intermediate too.
# Only this checkout's DerivedData directory is touched: every checkout's
# project has one, named by a hash of its workspace path, and info.plist in it
# records which workspace owns it. Another checkout may be building into its own.
derived_workspace() {
  local plist="$1/info.plist"
  [ -f "$plist" ] || return 0
  if command -v plutil >/dev/null 2>&1; then
    plutil -extract WorkspacePath raw -o - "$plist" 2>/dev/null && return 0
  fi
  sed -n '/<key>WorkspacePath<\/key>/{n;s/.*<string>\(.*\)<\/string>.*/\1/p;}' "$plist"
}

if [ "$(uname)" = "Darwin" ]; then
  IOS_DIR="$(cd "$MODULE_DIR/../../ios" 2>/dev/null && pwd -P || true)"
  for derived in "$HOME/Library/Developer/Xcode/DerivedData/VeloqDev-"*; do
    [ -d "$derived" ] || continue
    [ -n "$IOS_DIR" ] || continue
    workspace="$(derived_workspace "$derived")"
    [ -n "$workspace" ] || continue
    owner="$(cd "$(dirname "$workspace")" 2>/dev/null && pwd -P || true)"
    [ "$owner" = "$IOS_DIR" ] || continue
    echo "  Removing DerivedData Veloqrs xcframework intermediates"
    rm -rf "$derived"/Build/Products/*/XCFrameworkIntermediates/Veloqrs
  done
fi

if [ "$FULL" = true ]; then
  echo "✅ Full clean complete (including Rust compilation cache). Rebuild will recompile from scratch."
else
  echo "✅ Clean complete (Rust compilation cache preserved). Rebuild will use incremental compilation (~30s)."
fi
