/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by: npx tsx scripts/extract-ffi-exports.ts
 *
 * This file contains the expected FFI exports extracted from Rust source.
 * Used by tests to validate TypeScript bindings match Rust exports.
 *
 * After the domain object migration, most functions are methods on UniFFI Objects
 * (VeloqEngine, SectionManager, ActivityManager, etc.) rather than flat exports.
 * Only standalone functions that don't need engine state remain as flat exports.
 */

export interface FfiExportInfo {
  /** Rust function name (snake_case) */
  name: string;
  /** TypeScript function name (camelCase) */
  camelName: string;
  /** Source file relative to rust/veloqrs/src */
  file: string;
  /** Line number in source file */
  line: number;
}

/**
 * Standalone flat FFI exports from Rust source (not on UniFFI Objects).
 * Total: 4 exports
 */
export const FFI_EXPORTS: FfiExportInfo[] = [
  {
    name: 'get_download_progress',
    camelName: 'getDownloadProgress',
    file: 'ffi.rs',
    line: 43,
  },
  {
    name: 'start_fetch_and_store',
    camelName: 'startFetchAndStore',
    file: 'ffi.rs',
    line: 99,
  },
  {
    name: 'take_fetch_and_store_result',
    camelName: 'takeFetchAndStoreResult',
    file: 'ffi.rs',
    line: 403,
  },
  {
    name: 'compute_polyline_overlap',
    camelName: 'computePolylineOverlap',
    file: 'persistence.rs',
    line: 6886,
  },
];

/**
 * Expected TypeScript function names (camelCase) for standalone flat exports.
 */
export const EXPECTED_TS_FUNCTIONS = new Set<string>([
  'getDownloadProgress',
  'startFetchAndStore',
  'takeFetchAndStoreResult',
  'computePolylineOverlap',
]);

/**
 * Rust to TypeScript name mapping for standalone flat exports.
 */
export const RUST_TO_TS_NAME: Record<string, string> = {
  get_download_progress: 'getDownloadProgress',
  start_fetch_and_store: 'startFetchAndStore',
  take_fetch_and_store_result: 'takeFetchAndStoreResult',
  compute_polyline_overlap: 'computePolylineOverlap',
};

/**
 * UniFFI Objects that expose methods via #[uniffi::export] impl blocks.
 * These generate TypeScript classes in the generated bindings.
 */
export const UNIFFI_OBJECTS = [
  'VeloqEngine',
  'SectionManager',
  'ActivityManager',
  'RouteManager',
  'MapManager',
  'FitnessManager',
  'SettingsManager',
  'DetectionManager',
] as const;
